spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:@project.version@
  server:
    enable-self-preservation: false #eureka的自我保护，开发环境建议关闭
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
