[package]
name = "trpl_10_generic_type"
version = "0.1.0"
authors = ["fendoudebb <15317832520@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
