[package]
name = "trpl_14_doc_comment"
version = "0.1.0"
authors = ["fendoudebb <15317832520@163.com>"]
edition = "2018"
description = "test cargo crate"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
