spring:
  application:
    name: zuul

server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:@project.version@
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes: # 自定义路由
    myClient:
      path: /myClient/**
      serviceId: eureka-client
      # 携带Cookie。默认是敏感信息传递
      sensitiveHeaders:
    # 自定义路由简洁写法：路由到微服务的名称(spring.application.name)和新的路由地址
    eureka-client: /myClient2/**
  ignored-patterns:
    # set 写法：-
    - /myClient2/**
    - /**/test
  # 全部服务忽略敏感headers
  sensitive-headers:

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: info
    org.mybatis: debug
    java.sql: debug
    org.springframework.web: trace
